services:

  authzen-pdp:
    image: authzforce/authzen-pdp

    ports:
      - "8080:8080"
      # - "8443:8443"

    #environment:
      # Variable to customize JVM options (add -Dspring.profiles.active=xacml to enable XACML/REST profile only)
      #JAVA_OPTS: "-Dloader.path=/home/spring/extensions -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Djavax.xml.accessExternalSchema=all -Xms512m -Xmx1024m -server -Dspring.profiles.active=default"

    volumes:
      # The source path is given as example here. If you want to use AuthzForce PDP extensions, replace it with the path to the folder where you have the extension(s) JAR(s) with all dependencies that are not already part of the Docker image (i.e. that are not already dependencies of Maven artifact 'authzforce-ce-restful-pdp-cxf-spring-boot-server').
      - ./pdp/extensions:/home/spring/extensions:ro

      # Volume used to customize global Spring Boot settings (e.g. disable SSL or modify SSL settings), or change app-specific configuration (e.g. logging in 'logback.xml' file).
      - ./pdp/conf:/conf:ro
      # The wait-for-command script is needed when using the custom command down below.
      - ./wtfc.sh:/wtfc.sh